# 使用官方的 Python 3.11 slim 版本作為基底映像檔
FROM python:3.11-slim

# 設定工作目錄
WORKDIR /SoniTranslate

# 安裝系統相依套件
RUN apt-get update && \
    apt-get install -y \
    git \
    git-lfs \
    libcudnn8 && \
    rm -rf /var/lib/apt/lists/*

# 升級 pip 並指定版本
RUN python -m pip install --upgrade pip==23.1.2

# 下載 SoniTranslate 儲存庫
RUN git clone https://github.com/r3gm/SoniTranslate.git

# 進入 SoniTranslate 目錄
WORKDIR /SoniTranslate

# 修改 requirements 檔案以符合特定需求
RUN sed -i 's|git+https://github.com/R3gm/whisperX.git@cuda_11_8|git+https://github.com/R3gm/whisperX.git@cuda_12_x|' requirements_base.txt && \
    sed -i 's|fairseq==0.12.2 |https://github.com/liyaodev/fairseq/releases/download/v0.12.3.1/fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl|' requirements_extra.txt

# 安裝所需的 Python 套件
RUN pip install -r requirements_base.txt && \
    pip install -r requirements_extra.txt && \
    pip install ort-nightly-gpu --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/

# 安裝 PIPER_TTS (若指定安裝)
ARG Install_PIPER_TTS=True
RUN if [ "$Install_PIPER_TTS" = "True" ]; then pip install piper-tts==1.2.0; fi

# 安裝 Coqui XTTS (若指定安裝)
ARG Install_Coqui_XTTS=True
RUN if [ "$Install_Coqui_XTTS" = "True" ]; then pip install -r requirements_xtts.txt && pip install TTS==0.21.1 --no-deps; fi

# 安裝後不需要開放特定的 port（視情況而定，可以選擇性開放）
EXPOSE 5000

# 設定容器的預設命令 (此處為 bash，可以根據實際需求修改)
CMD ["bash"]
